## NumPy: Numerical Python

**NumPy (Numerical Python)** is a powerful Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. It is a fundamental package for scientific computing with Python.

NumPy is widely used in various fields such as mathematics, physics, engineering, data science, and machine learning. It offers a wide range of capabilities for performing numerical computations and handling numerical data effectively.

### Here are the key features of NumPy:

##### 1. Multi-dimensional array objects: 
NumPy provides the ndarray object, which allows you to create and manipulate arrays of any dimension. It supports one-dimensional, two-dimensional, and multi-dimensional arrays, enabling efficient storage and manipulation of large numerical datasets.

##### 2. Mathematical functions and operations: 
NumPy offers a comprehensive set of mathematical functions that can be applied element-wise to arrays. These functions include basic arithmetic operations (addition, subtraction, multiplication, division), trigonometric functions, exponential and logarithmic functions, statistical functions, linear algebra operations, and more.

##### 3. Broadcasting:
NumPy enables broadcasting, which allows for efficient operations between arrays of different shapes. Broadcasting automatically aligns arrays with different dimensions, eliminating the need for explicit loops and simplifying code.

##### 4. Array indexing and slicing:
NumPy provides powerful indexing and slicing capabilities to access and manipulate elements and subarrays within an array. You can use indexing to retrieve specific elements or ranges of elements, and slicing to extract subarrays based on specific conditions.

##### 5. Shape manipulation:
NumPy offers functions to manipulate the shape and size of arrays. You can reshape arrays, transpose them, concatenate multiple arrays, split arrays into smaller ones, and more. These operations provide flexibility in data manipulation and preparation.

##### 6. Array operations and computations:
NumPy provides efficient implementations of various array operations, such as element-wise operations, matrix multiplication, dot product, matrix inversion, eigenvalue decomposition, and more. These operations are optimized for speed and memory efficiency.

##### 7. Integration with other libraries:
NumPy seamlessly integrates with other libraries in the scientific Python ecosystem. It serves as a foundation for many higher-level libraries, such as SciPy (scientific computing), Matplotlib (plotting), pandas (data analysis), and scikit-learn (machine learning). NumPy arrays are commonly used as input and output data structures for these libraries.

##### 8. File input/output:
NumPy offers functions to read and write array data to/from disk. It supports various file formats, such as plain text, CSV, and binary formats. This feature facilitates data storage and sharing across different platforms.

##### 9. Random number generation: 
NumPy includes a random module that provides functions for generating random numbers and random arrays with different probability distributions. This capability is useful for simulations, modeling, and generating synthetic data.

### Import numpy

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5] #list

### Converting list to an array

#### Using np.array()

In [4]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
# Checking the data type
type(arr) 

numpy.ndarray

In [6]:
# Checking dimention
arr.ndim

1

In [35]:
arr.size

5

In [36]:
arr.shape

(5,)

In [40]:
arr.dtype

dtype('int64')

#### Using np.asarray()

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
# Checking data type
type(np.asarray(l))

numpy.ndarray

In [9]:
# Checking dimention
np.asarray(l).ndim

1

#### Using np.asanyarray()

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [11]:
# Checking data type
type(np.asanyarray(l))

numpy.ndarray

In [12]:
# Checking dimention
np.asanyarray(l).ndim

1

#### Creating 2-dim array

In [13]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Checking data type
type(arr1)

numpy.ndarray

In [16]:
# Checking dimension
arr1.ndim

2

In [37]:
arr1.size

6

In [38]:
arr1.shape

(2, 3)

In [39]:
arr1.dtype

dtype('int64')

#### Creating Matrix usins np.matrix()

In [17]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4, 5]])

In [18]:
type(mat)

numpy.matrix

In [19]:
# matrix to array
np.asarray(mat)

array([[1, 2, 3, 4, 5]])

In [20]:
type(np.asarray(mat))

numpy.ndarray

In [21]:
# matrix to matrix
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [22]:
type(np.asanyarray(mat))

numpy.matrix

#### NumPy provides different functions to create copies of arrays

1. Shallow copy (view):

**view():** This method creates a new array object that is a shallow copy of the original array. The new array is a view of the same data but with a different shape or strides. Changes made to the view will affect the original array, and vice versa.

2. Deep copy:

**np.copy():** This function creates a complete and independent copy of the original array. Any changes made to the copy will not affect the original array, and vice versa. It recursively copies all the data, including nested arrays.

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
# Shallow copy (view)
arr_shallow_copy = arr.view()

In [25]:
arr_shallow_copy[0] = 10

In [26]:
arr_shallow_copy

array([10,  2,  3,  4,  5])

In [27]:
# Change in arr_shallow_copy also changes arr
arr

array([10,  2,  3,  4,  5])

In [28]:
# Now arr becomes
arr

array([10,  2,  3,  4,  5])

In [29]:
# Deep copy
arr_deep_copy = np.copy(arr)

In [30]:
arr_deep_copy[0] = 20

In [31]:
arr_deep_copy

array([20,  2,  3,  4,  5])

In [32]:
# Deep copy donot change arr
arr

array([10,  2,  3,  4,  5])

#### The functions fromfunction(), fromstring(), and fromiter() are used to create arrays based on different sources of data.

#### numpy.fromfunction:
This function creates a new array by executing a specified function over each coordinate of the array. 
* It takes two parameters: the function and the shape of the resulting array. The function is called with N parameters, where N is the number of dimensions of the output array. The function should return the value to be placed at each coordinate.

In [33]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

#### numpy.fromiter:
This function creates an array from an iterable object such as a list or a generator. 
* It takes three parameters: the iterable object, the data type of the resulting array, and the number of elements to read from the iterable. If the number of elements is not specified, it reads until the iterator is exhausted.

In [27]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [28]:
iterable= (i*i for i in range(5))

In [29]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

#### numpy.fromstring: 
This function creates an array by reading data from a string. 
* It takes two parameters: the string containing the data and the data type of the resulting array. The string is interpreted as a 1-dimensional array, and each character is considered as an element of the array. 

In [30]:
np.fromstring('23 45 56', sep = ' ')

array([23., 45., 56.])

In [31]:
np.fromstring('23,45,56', sep = ',')

array([23., 45., 56.])

In [41]:
list(range(5))

[0, 1, 2, 3, 4]

In [42]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
#'float' object cannot be interpreted as an integer
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

* **np.arange** is a function in NumPy that creates an array of evenly spaced values within a specified range. 
* It is similar to the built-in **range** function in Python but returns an array instead of a list.
* The **np.arange** function returns a 1-dimensional NumPy array containing the generated values. The array is created with the specified data type, or if not provided, it uses the default data type based on the inputs.

In [45]:
np.arange(0.4,10.4,) #with step =1

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [47]:
list(np.arange(0.4,10.4, 0.5)) #with step =0.5

[0.4,
 0.9,
 1.4,
 1.9,
 2.4,
 2.9,
 3.4,
 3.9,
 4.4,
 4.9,
 5.4,
 5.9,
 6.4,
 6.9,
 7.4,
 7.9,
 8.4,
 8.9,
 9.4,
 9.9]

* **np.linspace** is a function in NumPy that creates an array of evenly spaced values within a specified interval.
* Unlike **np.arange**, which generates values with a specified step size, np.linspace generates values with a specified number of elements evenly distributed between the start and stop values.
* The **np.linspace** function returns a 1-dimensional NumPy array containing the generated values. The array is created with the specified data type, or if not provided, it uses the default data type based on the inputs.

In [47]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [48]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

#### Generating arrays

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
arr = np.ones((3,4))

In [54]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [57]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [58]:
np.empty((2,4))

array([[4.65537761e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [59]:
arr1 = np.eye(5)

In [60]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
import pandas as pd

In [62]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

#### Generating array with random numbers

In [63]:
np.random.rand(2,3) # mean and sd is anything

array([[0.90722341, 0.76011829, 0.00359084],
       [0.79185489, 0.02055809, 0.66231125]])

In [64]:
np.random.randn(2,3) #mean =0, sd=1

array([[ 1.53788237, -0.17210574, -0.9305231 ],
       [-0.95578894, -0.27007149,  1.47821512]])

In [64]:
arr2 = np.random.randint(1,5,(3,4))

In [65]:
arr2

array([[3, 4, 3, 3],
       [2, 3, 4, 4],
       [3, 3, 2, 2]])

In [66]:
arr2.size

12

In [67]:
arr2.shape

(3, 4)

In [68]:
arr2.reshape(6,2)

array([[3, 4],
       [3, 3],
       [2, 3],
       [4, 4],
       [3, 3],
       [2, 2]])

In [69]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [70]:
arr2.reshape(4,3)

array([[3, 4, 3],
       [3, 2, 3],
       [4, 4, 3],
       [3, 2, 2]])

In [71]:
# consider default i.e 3 instade of negetive(-1)
arr2.reshape(4,-1)

array([[3, 4, 3],
       [3, 2, 3],
       [4, 4, 3],
       [3, 2, 2]])

In [72]:
arr2.reshape(4,-30)

array([[3, 4, 3],
       [3, 2, 3],
       [4, 4, 3],
       [3, 2, 2]])

In [73]:
arr2.reshape(2,2,3)

array([[[3, 4, 3],
        [3, 2, 3]],

       [[4, 4, 3],
        [3, 2, 2]]])

In [74]:
arr2.reshape(2,2,3,1,1)

array([[[[[3]],

         [[4]],

         [[3]]],


        [[[3]],

         [[2]],

         [[3]]]],



       [[[[4]],

         [[4]],

         [[3]]],


        [[[3]],

         [[2]],

         [[2]]]]])

In [91]:
arr1 = np.random.randint(1,10,(5,6))

In [92]:
arr1

array([[4, 5, 2, 5, 4, 3],
       [6, 8, 3, 1, 1, 3],
       [7, 5, 2, 5, 7, 6],
       [7, 4, 8, 5, 7, 9],
       [5, 6, 1, 2, 3, 7]])

In [93]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False]])

In [94]:
# Filter
arr1[arr1>8]

array([9])

In [95]:
arr1

array([[4, 5, 2, 5, 4, 3],
       [6, 8, 3, 1, 1, 3],
       [7, 5, 2, 5, 7, 6],
       [7, 4, 8, 5, 7, 9],
       [5, 6, 1, 2, 3, 7]])

In [96]:
arr1[0]

array([4, 5, 2, 5, 4, 3])

In [97]:
arr1[0,[0,1]]

array([4, 5])

In [98]:
arr1[2:4,[2,3]]

array([[2, 5],
       [8, 5]])

In [99]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [100]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [101]:
arr2

array([[2, 2, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [102]:
arr1+arr2

array([[4, 3, 3],
       [2, 2, 4],
       [3, 2, 2]])

In [103]:
arr1 - arr2

array([[ 0, -1, -1],
       [ 0,  0,  0],
       [ 1,  0,  0]])

In [104]:
arr1*arr2

array([[4, 2, 2],
       [1, 1, 4],
       [2, 1, 1]])

In [105]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [106]:
arr2

array([[2, 2, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [107]:
arr1@arr2

array([[6, 6, 7],
       [5, 5, 6],
       [6, 6, 7]])

In [108]:
arr1/arr2

array([[1. , 0.5, 0.5],
       [1. , 1. , 1. ],
       [2. , 1. , 1. ]])

In [109]:
arr1/0

/tmp/ipykernel_77/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [110]:
arr = np.zeros((3,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
arr+5 #Broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [113]:
a = np.array([1,2,3,4])

In [114]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [115]:
b = np.array([[3,4,5]])

In [116]:
b.T

array([[3],
       [4],
       [5]])

In [117]:
arr1 = arr+b.T

In [118]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [119]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [120]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [121]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [122]:
np.min(arr1)

3.0

In [123]:
np.max(arr1)

5.0

In [124]:
arr1 = np.random.randint(1,5,(3,3))

In [125]:
arr1

array([[2, 4, 4],
       [1, 2, 4],
       [1, 3, 4]])

In [126]:
arr2 = np.random.randint(1,5,(3,3,3))

In [127]:
arr2

array([[[2, 4, 4],
        [4, 3, 1],
        [3, 1, 4]],

       [[3, 2, 1],
        [4, 3, 4],
        [1, 3, 3]],

       [[3, 2, 1],
        [2, 3, 4],
        [4, 1, 3]]])

In [128]:
arr1*arr2

array([[[ 4, 16, 16],
        [ 4,  6,  4],
        [ 3,  3, 16]],

       [[ 6,  8,  4],
        [ 4,  6, 16],
        [ 1,  9, 12]],

       [[ 6,  8,  4],
        [ 2,  6, 16],
        [ 4,  3, 12]]])

In [129]:
np.multiply(arr1,arr2)

array([[[ 4, 16, 16],
        [ 4,  6,  4],
        [ 3,  3, 16]],

       [[ 6,  8,  4],
        [ 4,  6, 16],
        [ 1,  9, 12]],

       [[ 6,  8,  4],
        [ 2,  6, 16],
        [ 4,  3, 12]]])

#### Array manupulation

In [130]:
arr = np.random.randint(1,10,[4,4])

In [131]:
arr

array([[9, 2, 1, 8],
       [4, 6, 4, 8],
       [5, 9, 7, 6],
       [7, 1, 3, 8]])

In [132]:
arr.reshape(8,2)

array([[9, 2],
       [1, 8],
       [4, 6],
       [4, 8],
       [5, 9],
       [7, 6],
       [7, 1],
       [3, 8]])

In [133]:
arr.T

array([[9, 4, 5, 7],
       [2, 6, 9, 1],
       [1, 4, 7, 3],
       [8, 8, 6, 8]])

In [134]:
arr

array([[9, 2, 1, 8],
       [4, 6, 4, 8],
       [5, 9, 7, 6],
       [7, 1, 3, 8]])

In [135]:
arr.flatten()

array([9, 2, 1, 8, 4, 6, 4, 8, 5, 9, 7, 6, 7, 1, 3, 8])

In [136]:
arr

array([[9, 2, 1, 8],
       [4, 6, 4, 8],
       [5, 9, 7, 6],
       [7, 1, 3, 8]])

In [137]:
np.expand_dims(arr, axis =1) #column wise

array([[[9, 2, 1, 8]],

       [[4, 6, 4, 8]],

       [[5, 9, 7, 6]],

       [[7, 1, 3, 8]]])

In [138]:
np.expand_dims(arr, axis =0)# row wise

array([[[9, 2, 1, 8],
        [4, 6, 4, 8],
        [5, 9, 7, 6],
        [7, 1, 3, 8]]])

In [139]:
data = np.array([[1],[2],[3]])

In [140]:
data

array([[1],
       [2],
       [3]])

In [141]:
np.squeeze(data)

array([1, 2, 3])

In [142]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [143]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [124]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Binary Operator

In [144]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [145]:
arr1

array([[8, 1, 7, 2],
       [4, 3, 1, 3],
       [2, 5, 3, 8]])

In [146]:
arr2

array([[8, 2, 9, 9],
       [8, 9, 3, 5],
       [1, 4, 7, 4]])

In [147]:
arr1+arr2

array([[16,  3, 16, 11],
       [12, 12,  4,  8],
       [ 3,  9, 10, 12]])

In [148]:
arr1*arr2

array([[64,  2, 63, 18],
       [32, 27,  3, 15],
       [ 2, 20, 21, 32]])

In [149]:
arr1/arr2

array([[1.        , 0.5       , 0.77777778, 0.22222222],
       [0.5       , 0.33333333, 0.33333333, 0.6       ],
       [2.        , 1.25      , 0.42857143, 2.        ]])

In [150]:
arr1-arr2

array([[ 0, -1, -2, -7],
       [-4, -6, -2, -2],
       [ 1,  1, -4,  4]])

In [151]:
arr1**arr2

array([[16777216,        1, 40353607,      512],
       [   65536,    19683,        1,      243],
       [       2,      625,     2187,     4096]])

In [135]:
~arr1

array([[ -3, -10,  -3,  -6],
       [ -5,  -4,  -4, -10],
       [ -4,  -8,  -4,  -3]])

In [136]:
arr1

array([[2, 9, 2, 5],
       [4, 3, 3, 9],
       [3, 7, 3, 2]])

In [137]:
arr1>arr2

array([[False,  True, False,  True],
       [ True, False, False,  True],
       [False,  True, False, False]])

#### string functions

In [152]:
arr = np.array(["saikat","mondal"])

In [153]:
arr

array(['saikat', 'mondal'], dtype='<U6')

In [154]:
np.char.upper(arr)

array(['SAIKAT', 'MONDAL'], dtype='<U6')

In [155]:
np.char.capitalize(arr)

array(['Saikat', 'Mondal'], dtype='<U6')

In [156]:
np.char.title(arr)

array(['Saikat', 'Mondal'], dtype='<U6')

#### Mathematical Function

In [158]:
arr1

array([[8, 1, 7, 2],
       [4, 3, 1, 3],
       [2, 5, 3, 8]])

In [159]:
np.sin(arr1)

array([[ 0.98935825,  0.84147098,  0.6569866 ,  0.90929743],
       [-0.7568025 ,  0.14112001,  0.84147098,  0.14112001],
       [ 0.90929743, -0.95892427,  0.14112001,  0.98935825]])

In [160]:
np.cos(arr1)

array([[-0.14550003,  0.54030231,  0.75390225, -0.41614684],
       [-0.65364362, -0.9899925 ,  0.54030231, -0.9899925 ],
       [-0.41614684,  0.28366219, -0.9899925 , -0.14550003]])

In [161]:
np.tan(arr1)

array([[-6.79971146,  1.55740772,  0.87144798, -2.18503986],
       [ 1.15782128, -0.14254654,  1.55740772, -0.14254654],
       [-2.18503986, -3.38051501, -0.14254654, -6.79971146]])

In [162]:
np.log10(arr1)

array([[0.90308999, 0.        , 0.84509804, 0.30103   ],
       [0.60205999, 0.47712125, 0.        , 0.47712125],
       [0.30103   , 0.69897   , 0.47712125, 0.90308999]])

In [163]:
np.exp(arr1)

array([[2.98095799e+03, 2.71828183e+00, 1.09663316e+03, 7.38905610e+00],
       [5.45981500e+01, 2.00855369e+01, 2.71828183e+00, 2.00855369e+01],
       [7.38905610e+00, 1.48413159e+02, 2.00855369e+01, 2.98095799e+03]])

In [164]:
np.power(arr1,2)

array([[64,  1, 49,  4],
       [16,  9,  1,  9],
       [ 4, 25,  9, 64]])

In [165]:
arr1

array([[8, 1, 7, 2],
       [4, 3, 1, 3],
       [2, 5, 3, 8]])

In [166]:
np.mean(arr1)

3.9166666666666665

In [167]:
np.median(arr1)

3.0

In [168]:
np.std(arr1)

2.4309920243024705

In [169]:
np.var(arr1)

5.909722222222224

In [170]:
np.min(arr1)

1

In [171]:
np.max(arr1)

8

#### Arithmetic Operations

In [172]:
arr1

array([[8, 1, 7, 2],
       [4, 3, 1, 3],
       [2, 5, 3, 8]])

In [173]:
arr2

array([[8, 2, 9, 9],
       [8, 9, 3, 5],
       [1, 4, 7, 4]])

In [174]:
arr1-arr2

array([[ 0, -1, -2, -7],
       [-4, -6, -2, -2],
       [ 1,  1, -4,  4]])

In [175]:
np.subtract(arr1,arr2)

array([[ 0, -1, -2, -7],
       [-4, -6, -2, -2],
       [ 1,  1, -4,  4]])

In [166]:
np.multiply(arr1,arr2)

array([[ 8, 18, 10, 10],
       [ 4,  9, 18, 36],
       [21, 14,  9,  6]])

In [176]:
np.mod(arr1,arr2)

array([[0, 1, 7, 2],
       [4, 3, 1, 3],
       [0, 1, 3, 0]])

In [177]:
np.power(arr1,arr2)

array([[16777216,        1, 40353607,      512],
       [   65536,    19683,        1,      243],
       [       2,      625,     2187,     4096]])

In [178]:
np.sqrt(arr1)

array([[2.82842712, 1.        , 2.64575131, 1.41421356],
       [2.        , 1.73205081, 1.        , 1.73205081],
       [1.41421356, 2.23606798, 1.73205081, 2.82842712]])

#### Statistical function

In [180]:
np.mean(arr1)

3.9166666666666665

In [181]:
np.std(arr1)

2.4309920243024705

In [182]:
np.median(arr1)

3.0

In [183]:
np.var(arr1)

5.909722222222224

#### Sort, search, Counting function

In [184]:
arr = np.array([4,2,8,5,3,9,12,56])

In [185]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [186]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [187]:
np.searchsorted(arr,6)

5

In [188]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [189]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [190]:
np.count_nonzero(arr1)

6

In [191]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9]),)

In [191]:
np.extract(arr1>2,arr1)

array([324, 645,  65,   6,   6, 234])

#### Byte swapping

In [192]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [193]:
arr.byteswap()

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [194]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [195]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [196]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

#### Matrix Libraries

In [198]:
import numpy.matlib as nm

In [199]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [200]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [201]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

#### Linear Algebra

In [203]:
arr1 = np.random.randint([[2,3],[4,5]])

In [204]:
arr1

array([[0, 0],
       [0, 2]])

In [205]:
arr2 = np.random.randint([[5,3],[2,5]])

In [206]:
arr2

array([[3, 1],
       [0, 4]])

In [207]:
np.dot(arr1,arr2)

array([[0, 0],
       [0, 8]])

In [208]:
arr1@arr2

array([[0, 0],
       [0, 8]])

#### Some more functionality

In [209]:
arr = [1,2,3,4,5,5,6,6,2,3]

In [210]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [211]:
np.flip(arr)

array([3, 2, 6, 6, 5, 5, 4, 3, 2, 1])

In [212]:
np.argsort(arr)

array([0, 1, 8, 2, 9, 3, 4, 5, 6, 7])

In [213]:
np.argmax(arr)

6

In [214]:
np.count_nonzero(arr)

10

#### There are lots more in NumPy.